apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jakebriscoe.com
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/jakebriscoe/jakebriscoe.com-infrastructure"
    targetRevision: HEAD
    path: .
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  # syncPolicy:
  #   automated:
  #     prune: true
