apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: web-client

resources:
  - ../../base/

namePrefix: web-client-

patchesStrategicMerge:
  - deployment.yaml
