apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: game-service

resources:
  - ../../base/

namePrefix: game-

patchesStrategicMerge:
  - deployment.yaml
