apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: user-service

resources:
  - ../../base/

namePrefix: user-

patchesStrategicMerge:
  - deployment.yaml
