apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: service
          image: postgres:13
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
