apiVersion: batch/v1
kind: Job
metadata:
  name: db-setup
spec:
  backoffLimit: 12
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-setup
          image: jakebriscoe/spotify-postgres-startup:v0.51.0
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - secretRef:
                name: postgres-secret
      dnsPolicy: ClusterFirst
