apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: postgres

# TODO don't expose port 80 and 443
resources:
  - deployment.yaml
  - service.yaml
  # - ../../base/
  - secret.yaml
  - role.yaml
  - role-binding.yaml
  - job.yaml

namePrefix: postgres-
# patchesStrategicMerge:
#   - deployment.yaml
#   - service.yaml
