kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-secret-creator-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev
roleRef:
  kind: Role
  name: postgres-secret-creator
  apiGroup: rbac.authorization.k8s.io
