# TODO remove credentials from git
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==
  POSTGRES_DB: bXlkYXRhYmFzZQ==
