apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: service
          image: service-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args: ["--namespace=$(MY_NAMESPACE)"]
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
