apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: service
          image: jakebriscoe/spotify-leaderboard-service:v0.32.0
