apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: leaderboard-service

resources:
  - ../../base/

namePrefix: leaderboard-

patchesStrategicMerge:
  - deployment.yaml
