apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: service
          image: jakebriscoe/spotify-content-service:v0.33.0
