apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  app: content-service

resources:
  - ../../base/

namePrefix: content-

patchesStrategicMerge:
  - deployment.yaml
